### ISSUE TITLE
Two additions for Rutgers

### ISSUE THREAD

**Issue by buyske** [DDD-Moore/datasci-at-R1-institutions#1]
In addition to the online program, Rutgers has a two-track in-person Masters degree in Data Science. The statistics track can be found at 
http://msds-stat.rutgers.edu/about-the-program/msds-overview
while the CS track has the link https://ms.cs.rutgers.edu/msds/

Thanks
Steve Buyske
buyske@stat.rutgers.edu

**Comment by strasser** [comment]
Added! Thanks!
